/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTodosRouteImport } from './routes/api/todos'
import { Route as ApiProfilesIndexRouteImport } from './routes/api/profiles/index'
import { Route as ApiHealthIndexRouteImport } from './routes/api/health/index'
import { Route as ApiUserMeRouteImport } from './routes/api/user/me'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiProfilesActiveRouteImport } from './routes/api/profiles/active'
import { Route as ApiProfilesProfileIdRouteImport } from './routes/api/profiles/$profileId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodosRoute = ApiTodosRouteImport.update({
  id: '/api/todos',
  path: '/api/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesIndexRoute = ApiProfilesIndexRouteImport.update({
  id: '/api/profiles/',
  path: '/api/profiles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthIndexRoute = ApiHealthIndexRouteImport.update({
  id: '/api/health/',
  path: '/api/health/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserMeRoute = ApiUserMeRouteImport.update({
  id: '/api/user/me',
  path: '/api/user/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesActiveRoute = ApiProfilesActiveRouteImport.update({
  id: '/api/profiles/active',
  path: '/api/profiles/active',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfilesProfileIdRoute = ApiProfilesProfileIdRouteImport.update({
  id: '/api/profiles/$profileId',
  path: '/api/profiles/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/todos': typeof ApiTodosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/profiles/$profileId': typeof ApiProfilesProfileIdRoute
  '/api/profiles/active': typeof ApiProfilesActiveRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/user/me': typeof ApiUserMeRoute
  '/api/health/': typeof ApiHealthIndexRoute
  '/api/profiles/': typeof ApiProfilesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/todos': typeof ApiTodosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/profiles/$profileId': typeof ApiProfilesProfileIdRoute
  '/api/profiles/active': typeof ApiProfilesActiveRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/user/me': typeof ApiUserMeRoute
  '/api/health': typeof ApiHealthIndexRoute
  '/api/profiles': typeof ApiProfilesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/todos': typeof ApiTodosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/profiles/$profileId': typeof ApiProfilesProfileIdRoute
  '/api/profiles/active': typeof ApiProfilesActiveRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/user/me': typeof ApiUserMeRoute
  '/api/health/': typeof ApiHealthIndexRoute
  '/api/profiles/': typeof ApiProfilesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/todos'
    | '/api/auth/$'
    | '/api/profiles/$profileId'
    | '/api/profiles/active'
    | '/api/trpc/$'
    | '/api/user/me'
    | '/api/health/'
    | '/api/profiles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/todos'
    | '/api/auth/$'
    | '/api/profiles/$profileId'
    | '/api/profiles/active'
    | '/api/trpc/$'
    | '/api/user/me'
    | '/api/health'
    | '/api/profiles'
  id:
    | '__root__'
    | '/'
    | '/api/todos'
    | '/api/auth/$'
    | '/api/profiles/$profileId'
    | '/api/profiles/active'
    | '/api/trpc/$'
    | '/api/user/me'
    | '/api/health/'
    | '/api/profiles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiTodosRoute: typeof ApiTodosRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiProfilesProfileIdRoute: typeof ApiProfilesProfileIdRoute
  ApiProfilesActiveRoute: typeof ApiProfilesActiveRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiUserMeRoute: typeof ApiUserMeRoute
  ApiHealthIndexRoute: typeof ApiHealthIndexRoute
  ApiProfilesIndexRoute: typeof ApiProfilesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/todos': {
      id: '/api/todos'
      path: '/api/todos'
      fullPath: '/api/todos'
      preLoaderRoute: typeof ApiTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/': {
      id: '/api/profiles/'
      path: '/api/profiles'
      fullPath: '/api/profiles/'
      preLoaderRoute: typeof ApiProfilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/': {
      id: '/api/health/'
      path: '/api/health'
      fullPath: '/api/health/'
      preLoaderRoute: typeof ApiHealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/me': {
      id: '/api/user/me'
      path: '/api/user/me'
      fullPath: '/api/user/me'
      preLoaderRoute: typeof ApiUserMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/active': {
      id: '/api/profiles/active'
      path: '/api/profiles/active'
      fullPath: '/api/profiles/active'
      preLoaderRoute: typeof ApiProfilesActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profiles/$profileId': {
      id: '/api/profiles/$profileId'
      path: '/api/profiles/$profileId'
      fullPath: '/api/profiles/$profileId'
      preLoaderRoute: typeof ApiProfilesProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiTodosRoute: ApiTodosRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiProfilesProfileIdRoute: ApiProfilesProfileIdRoute,
  ApiProfilesActiveRoute: ApiProfilesActiveRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiUserMeRoute: ApiUserMeRoute,
  ApiHealthIndexRoute: ApiHealthIndexRoute,
  ApiProfilesIndexRoute: ApiProfilesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
